spring.application.name=lab-resource-utilization
spring.datasource.url=jdbc:postgresql://localhost:5432/lab_resource_db
spring.datasource.username=postgres
spring.datasource.password=Santhu@23

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081