spring.application.name=lab-resource-utilization

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
<<<<<<< HEAD
spring.datasource.password=dh@rshni03
=======
spring.datasource.password=Santhu@23
>>>>>>> 74d96258e77b4b7784f75e2c2b0c54eabe23de0c

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Enable data.sql seed file to run on startup
spring.sql.init.mode=always

server.port=8081